#!/usr/bin/env python3
"""Build examples/RESULTS.md from the manifests and results.tsv.

Reports per task, never aggregate-only: a change that lifts the mean while
breaking two tasks is a different decision, and the aggregate hides it.

Also splits arm B by whether the skill actually fired. A run where the skill
never loaded is not a failed measurement of skill content — it is a successful
measurement of the description. Collapsing the two hides which half works.
"""
from __future__ import annotations
import json, pathlib, statistics as st, sys
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "graders")); sys.path.insert(0, str(ROOT / "tasks"))
import rubrics                      # noqa: E402
from tasks import BY_ID, TASKS      # noqa: E402


def load(arm: str) -> list[dict]:
    mf = ROOT / "runs" / f"manifest_{arm}.jsonl"
    return [json.loads(l) for l in mf.read_text().splitlines() if l.strip()] if mf.exists() else []


def score_of(row: dict) -> float | None:
    p = ROOT / "runs" / row["arm"] / row["file"]
    return rubrics.grade(row["task"], p.read_text())["score"] if p.exists() else None


def fmt(x, nd=2):
    return "—" if x is None else f"{x:.{nd}f}"


def main() -> int:
    rows = load("a") + load("b")
    if not rows:
        print("nothing recorded yet", file=sys.stderr); return 1

    by = defaultdict(list)                 # (task, arm) -> [score]
    fired = defaultdict(list)              # task -> [score] where skill fired
    meta = defaultdict(list)               # arm -> [row]
    for r in rows:
        s = score_of(r)
        if s is None:
            continue
        by[(r["task"], r["arm"])].append(s)
        meta[r["arm"]].append(r)
        if r["arm"] == "b" and r.get("skill_triggered"):
            fired[r["task"]].append(s)

    out = ["# Results", "",
           "Generated by `examples/report.py`. Per task, never aggregate-only.", ""]

    # ---- headline, per task
    out += ["## Per task", "",
            "| task | kind | skill | A mean | A sd | B mean | B sd | delta | n (A/B) | fired |",
            "|---|---|---|---|---|---|---|---|---|---|"]
    deltas_by_kind = defaultdict(list)
    for t in TASKS:
        tid = t["id"]
        a, b = by.get((tid, "a"), []), by.get((tid, "b"), [])
        if not a and not b:
            continue
        ma = st.mean(a) if a else None
        mb = st.mean(b) if b else None
        sa = st.stdev(a) if len(a) > 1 else 0.0
        sb = st.stdev(b) if len(b) > 1 else 0.0
        d = (mb - ma) if (ma is not None and mb is not None) else None
        if d is not None:
            deltas_by_kind[t["kind"]].append(d)
        nb_fired = len(fired.get(tid, []))
        out.append(f"| {tid} | {t['kind']} | {t['skill']} | {fmt(ma)} | {fmt(sa)} | "
                   f"{fmt(mb)} | {fmt(sb)} | {fmt(d,2) if d is None else f'{d:+.2f}'} | "
                   f"{len(a)}/{len(b)} | {nb_fired}/{len(b)} |")

    # ---- by kind. The traps and controls are the interesting rows.
    out += ["", "## By task kind", "",
            "The controls are where skills can *lose*: there the correct behaviour is "
            "not to apply the skill. A negative delta on a control is the most "
            "important number in this file.", "",
            "| kind | tasks | mean delta | worst task delta |", "|---|---|---|---|"]
    for kind in ("positive", "trap", "control"):
        ds = deltas_by_kind.get(kind, [])
        if not ds:
            continue
        out.append(f"| {kind} | {len(ds)} | {st.mean(ds):+.2f} | {min(ds):+.2f} |")

    # ---- triggering
    b_rows = meta.get("b", [])
    n_fired = sum(1 for r in b_rows if r.get("skill_triggered"))
    out += ["", "## Triggering", "",
            f"The skill fired in **{n_fired} of {len(b_rows)}** arm-B runs "
            f"({100*n_fired/len(b_rows):.0f}%)." if b_rows else "", ""]
    if b_rows and n_fired < len(b_rows):
        out += ["Runs where it never fired measure the *description*, not the content. "
                "Conditional means, over fired runs only:", "",
                "| task | B mean (all) | B mean (fired only) | n fired |", "|---|---|---|---|"]
        for t in TASKS:
            tid, f = t["id"], fired.get(t["id"], [])
            b = by.get((tid, "b"), [])
            if b and f and len(f) != len(b):
                out.append(f"| {tid} | {st.mean(b):.2f} | {st.mean(f):.2f} | {len(f)}/{len(b)} |")

    # ---- effort confound
    out += ["", "## Effort check", "",
            "If arm B simply did more work, the gain may not be the skill.", "",
            "| arm | runs | mean turns | mean tools/run |", "|---|---|---|---|"]
    for arm in ("a", "b"):
        rs = meta.get(arm, [])
        if not rs:
            continue
        turns = [r["turns"] for r in rs if r.get("turns") is not None]
        tools = [len(r.get("tools_used") or []) for r in rs]
        out.append(f"| {arm} | {len(rs)} | {fmt(st.mean(turns),1) if turns else '—'} | "
                   f"{fmt(st.mean(tools),1) if tools else '—'} |")

    out += ["", "## Threats to validity", "",
            "- Both arms run inside a Claude Code session, which carries a large constant "
            "system prompt and a tool loop. That is held constant, but it widens variance "
            "relative to a single-turn API call.",
            "- n is small. Treat per-task deltas smaller than the reported sd as noise.",
            "- Arm B is the only arm with skills installed; nothing else differs. "
            "`check_contamination.py` verifies arm A never read one.",
            "- Grader rubrics were pre-registered and are validated against fixtures "
            "(`validate_graders.py`), but they are still proxies for code quality.", ""]

    (ROOT / "RESULTS.md").write_text("\n".join(out))
    print(f"wrote {ROOT / 'RESULTS.md'}")
    print("\n".join(out[:20]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
